config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  resources :users, only: [:create, :new, :show]
  resources :sessions, only: :create

  get 'login' => 'sessions#new', :as => :login
  delete 'logout' => 'sessions#destroy', :as => :logout

  resources :projects do
    resources :rewards, only: [:index, :create, :new, :destroy] do #, shallow: true
      resources :pledges, only: [:index, :new, :create, :show]
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
  belongs_to :backer, class_name: 'User'
  belongs_to :reward

  delegate :project, to: :reward, allow_nil: true

  validates :backer, presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :owner, class_name: 'User'
  has_many :rewards
  has_many :pledges, through: :rewards
  has_many :backers, through: :pledges, class_name: 'User'

  accepts_nested_attributes_for :rewards, :reject_if => :all_blank, :allow_destroy => true

  validates :goal, presence: true, numericality: true
  validates :start_date, presence: true
  validates :end_date, presence: true

  validate :start_date_cannot_be_in_the_past
  validate :cannot_be_finished_before_start_date
  validate :max_project_duration
  validate :funds_remaining_to_reach_goal

  def started?
    DateTime.now >= self.start_date
  end

  def ended?
    DateTime.now < self.end_date
  end

  def days_remaining_until_start_date
    if started?
      (self.end_date.to_date - DateTime.now.to_date).to_i
    else
      false
    end
  end

  def days_remaining_until_end_date
    unless started?
      (self.start_date.to_date - DateTime.now.to_date).to_i
    else
      false
    end
  end

  def funds_remaining_to_reach_goal
    total = self.goal - self.pledges.sum('amount')
    if total > 0
      return total
    else
      return 0
    end
  end

  def funds_raised
    self.rewards.sum('amount')
  end

  def pledges_by_user(user)
    self.pledges.where(backer: user)
  end

  # Custom Validations

  def cannot_be_finished_before_start_date
    if self.end_date.present? && self.end_date < self.start_date
      errors.add(:end_date, "cannot finish before start date")
    end
  end

  def start_date_cannot_be_in_the_past
    if self.start_date.present? && self.start_date < DateTime.now.beginning_of_day
      errors.add(:start_date, "cannot be in the past.")
    end
  end

  def max_project_duration
    if self.end_date.present? && self.start_date.present?
      if (self.end_date - self.start_date) > 1.month
        errors.add(:end_date, "project can't be longer than 1 month long")
      end
    end
  end
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  belongs_to :project
  has_many :pledges

  def remaining
    self.limit - self.pledges.count
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, on: :create
  validates :password, confirmation: true, on: :create
  validates :password_confirmation, presence: true, on: :create

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, uniqueness: true

  has_many :pledges, foreign_key: 'backer_id'
  has_many :rewards, through: :pledges

  has_many :owned_projects, class_name: 'Project', foreign_key: 'owner_id'
  has_many :backed_projects, through: :pledges, source: :backer

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def total_pledges
    self.rewards.sum('amount')
  end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
  def new
    @pledge = Pledge.new
  end

  def create
    @pledge = Pledge.new
    @pledge.reward = Reward.find(params[:reward_id])
    @pledge.backer = current_user
    if @pledge.save
      flash[:notice] = "Thanks for pledging $#{@pledge.reward.amount}0!"
    else
      flash[:alert] = "Unable to make pledge"
      flash[:error] = @pledge.errors.full_messages.first
    end
    redirect_to @pledge.reward.project
  end

  def show
    @pledge = Pledge.find(params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all

    @projects= Project.order('projects.created_at DESC').page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @project = Project.new
    @project.start_date = Date.today + 1.day
    @project.end_date = Date.today + 14.days
  end

  def show
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(project_params)
    @project.owner = current_user
    if @project.save
      flash[:notice] = "Project #{@project.name} successfully created."
      redirect_to projects_url
    else
      flash[:alert] = "Unable to create new project."
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @project.update_attributes(project_params)
    if @project.save
      flash[:notice] = "Successfully updated the #{@project.name} project"
      redirect_to @project
    else
      flash[:alert] = "There was an error updating #{@project.name}"
      render :edit
    end
  end

  private
  def project_params
    params.require(:project).permit(:name, :description, :start_date, :end_date,
      :goal, rewards_attributes: [:id, :name, :description, :amount, :limit, :_destroy])
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  def index
    @rewards = Reward.all
  end

  def new
    @reward = Reward.new
  end

  def create
    @reward = Reward.new(reward_params)
    if @reward.save
      flash[:notice] = "Success! Your reward was created."
      format.html { redirect_to project_url(@project) }
      format.js
    else
      flash[:notice] = "Woops. Your reward couldn't be created."
      format.html { render :new }
      format.js { }
    end
  end

  private
  def reward_params
    params.require(:reward).permit(:name, :description, :amount, :limit)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      flash[:notice] = 'Login successful'
      redirect_to projects_url
    else
      flash[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(root_url, notice: 'Logged out')
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      auto_login(@user)
      redirect_to projects_url
      flash[:notice] = "You've signed up!"
    else
      render :new
      flash[:alert] = "Please try again."
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Biggunzfunder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, msg| %>
  <% if name != "error" %>
    <%= content_tag :div, msg, class: name %>
  <% end %>
<% end %>

<% if current_user %>
  <p class="login">
    Logged in as <strong><%= current_user.full_name %></strong> |
    <%= link_to 'Log out', logout_path(:current), method: :delete %>
  </p>
<% else %>
  <p class="login">
    <%= link_to 'Create an account', new_user_path %>
    <%= link_to 'Log in', login_path  %>
  </p>
<% end %>

<%= yield %>

</body>
</html>

app/views/pledges/create.html.erb
<h1>Pledges#create</h1>
<p>Find me in app/views/pledges/create.html.erb</p>

app/views/pledges/new.html.erb
<h1>Pledges#new</h1>
<p>Find me in app/views/pledges/new.html.erb</p>

app/views/pledges/show.html.erb
<h1>Pledges#show</h1>
<p>Find me in app/views/pledges/show.html.erb</p>

app/views/projects/_add_reward.html.erb
<h2>Add Rewards to your Project</h2>

<%= fields_for @rewards do |f| %>

  <div class="reward">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="reward">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="reward">
    <%= f.label :amount %>
    <%= f.number_field :amount %>
  </div>

  <div class="reward">
    <%= f.label :limit %>
    <%= f.number_field :limit %>
  </div>

  <div class="submit">
    <%= f.button "Create Reward" %>
  </div>

<% end %>

app/views/projects/_pledges.html.erb
<aside class="pledges">
  <%= form_for [@project, @pledge :remote => true ] do |f| %>
    <% if flash[:error] %>
      <div class="error" style="color: red;">
        <%= flash[:error] %>
      </div>
    <% end %>
    <fieldset>
      <legend>Make a pledge on this project</legend>
      <div class="errors">
        <% if @pledge.errors.any? %>
          <% @pledge.errors.full_messages.each do |error| %>
            <p><%= error %></p>
          <% end %>
        <% end %>
      </div>
      <div class="field">
        <%= f.label :amount %>
        $<%= f.text_field :amount %>.00
      </div>
      <div class="field">
        <%= f.button "Make Pledge" %>
      </div>
    </fieldset>
  <% end %>

  <% if current_user %>
    <h3>Your pledges to this project</h3>

    <ul class="user pledges">
      <% @pledges.each do |pledge| %>
        <li>
          <div class="pledge date"><%= pledge.created_at.strftime("%A, %B %d %Y") %></div>
          <div class="pledge amount"><%= number_to_currency(pledge.amount) %></div>
        </li>
      <% end %>
    </ul>
  <% end %>
</aside>

app/views/projects/_project_form.html.erb
<%= form_for @project do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :start_date %>
    <%= f.date_field :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %>
    <%= f.date_field :end_date %>
  </div>
  <div class="field">
    <%= f.label :goal %>
    $<%= f.number_field :goal %>.00
  </div>

  <h4>Add rewards</h4>

  <div id="rewards">
    <%= f.fields_for :rewards do |reward_fields| %>
      <%= render 'reward_fields', f: reward_fields %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'Add reward', f, :rewards %>
    </div>
  </div>

  <div class="field">
    <%= f.button "Create Project" %>
  </div>
<% end %>

app/views/projects/_reward_fields.html.erb
<div class="reward">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div class="reward">
  <%= f.label :description %>
  <%= f.text_area :description %>
</div>

<div class="reward">
  <%= f.label :amount %>
  <%= f.number_field :amount %>
</div>

<div class="reward">
  <%= f.label :limit %>
  <%= f.number_field :limit %>
</div>

app/views/projects/_show_reward.html.erb
<h3>Reward: <%= reward.name %></h3>
<p><%= reward.description %></p>

<dl class="rewards">
    <dt>Amount</dt>
    <dd><%= reward.amount %></dd>

    <dt>Limit</dt>
    <dd><%= reward.limit %></dd>

    <dt>Remaining:</dt>
    <dd><%= reward.remaining %></dd>

    <%= form_for [@project,reward,reward.pledges.build] do |f| %>
      <%= f.button 'Make pledge!' %>
    <% end %>
</dl>

app/views/projects/edit.html.erb
<h2>Editing project: <%= @project.name %></h2>

<%= render 'project_form' %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<% if current_user %>
  <%= link_to "Add new project", new_project_path %>
<% end %>

<h1><small><%= page_entries_info @projects %></small></h1>


<ul id="projects">
  <% @projects.each do |p| %>
    <li><%= link_to p.name, p %></li>
  <% end %>
</ul>

<%= paginate @projects %>

app/views/projects/index.js.erb
$('#projects').html("<%= j(render @projects) %>");

app/views/projects/new.html.erb
<h2>Create Project</h2>

<%= render 'project_form' %>

app/views/projects/show.html.erb
<h2><%= @project.name %></h2>

<% unless @project.started? %>
  <% if current_user === @project.owner %>
    <p><%= link_to "Edit project", edit_project_path(@project) %></p>
  <% end %>
<% end %>

<% if @project.errors.any? %>
  <ul>
    <%= @project.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

<section class="project">
  <dl>
    <dt>Description</dt>
    <dd><%= @project.description %></dd>

    <dt>Start Date</dt>
    <dd><%= @project.start_date.strftime("%B %e, %Y") %></dd>

    <dt>End Date</dt>
    <dd><%= @project.end_date.strftime("%B %e, %Y") %></dd>

    <% unless @project.started? %>
      <dt>Days remaining until start date</dt>
      <dd><%= @project.days_remaining_until_end_date %></dd>
    <% end %>

    <% unless @project.ended? %>
      <dt>Days remaining until end date</dt>
      <dd><%= @project.days_remaining_until_end_date %></dd>
    <% end %>

    <dt>Goal</dt>
    <dd><%= number_to_currency(@project.goal) %></dd>

    <dt>Funds raised</dt>
    <dd><%= number_to_currency(@project.funds_raised) %></dd>

    <dt>Amount remaining until goal is reached</dt>
    <dd><%= number_to_currency(@project.funds_remaining_to_reach_goal) %></dd>

    <dt>Project Owner</dt>
    <dd><%= @project.owner.full_name %></dd>
  </dl>
</section>

<aside class="pledges">
  <% if @project.pledges_by_user(current_user).count > 0 %>
    <h3>You've made the following pledges to this project!</h3>
    <% @project.pledges_by_user(current_user).each do |pledge| %>
      <p>
        <%= number_to_currency(pledge.reward.amount) %>
        (Reward: <strong><%= pledge.reward.name %></strong>)
      </p>
    <% end %>
  <% end %>
</aside>

<section class="rewards">
  <% @project.rewards.each do |reward| %>
    <%= render partial: 'show_reward', locals: {reward: reward} %>
  <% end %>
</section>

app/views/rewards/create.html.erb
<h1>Rewards#create</h1>
<p>Find me in app/views/rewards/create.html.erb</p>

app/views/rewards/create.js.erb
alert("I’m responding to your request!");

app/views/rewards/destroy.html.erb
<h1>Rewards#destroy</h1>
<p>Find me in app/views/rewards/destroy.html.erb</p>

app/views/rewards/index.html.erb
<h1>Rewards#index</h1>
<p>Find me in app/views/rewards/index.html.erb</p>

app/views/rewards/new.html.erb
<h1>Rewards#new</h1>
<p>Find me in app/views/rewards/new.html.erb</p>

app/views/rewards/show.html.erb
<section class="reward">
  <dl>
    <dt>Name</dt>
    <dd><%= reward.name %></dd>

    <dt>Description</dt>
    <dd><%= reward.description %></dd>

    <dt>Amount</dt>
    <dd><%= reward.amount %></dd>

    <dt>Limit</dt>
    <dd><%= reward.limit %></dd>
  </dl>
</section>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div class="error_message">

      <h2><%= pluralize(@user.errors.count, "error") %> prohibited your account from being created:</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>

    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="button">
    <%= f.submit %>
  </div>

<% end %>

app/views/users/show.html.erb
<h2>User Profile</h2>

<p>
  <strong>Name:</strong>
  <%= @user.full_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Total Pledges:</strong>
  <%= number_to_currency(@user.total_pledges) %>
</p>

<strong>Projects backed:</strong>
<ul class="rewards">
  <% @user.rewards.each do |reward| %>
    <li class="user reward">
      <p>
        Pledged <%= number_to_currency(reward.amount) %> to
        <%= link_to reward.project.name, reward.project %>.
      </p>
      <p>
        Reward: <%= reward.name %>
      </p>
    </li>
  <% end %>
</ul>